setup:
    simple_dir : '/home/s1/smau/software/simple'
    #simple_dir : '/Users/keithbechtol/Documents/DES/code/simple'

output:
    results_dir : 'results_dir'
    log_dir     : 'log_dir'
    save_dir    : 'save_dir'

batch:
    jobs: 20 # <= 20 for DES cluster computers!

survey: 'y3_gold_2_0' # parameter to change for runs across different data
#survey: 'panstarrs'
#survey: 'bliss'

y3_gold_2_0:
    mode : 0 # 0: real, 1: real+sim
    sim_population : '/home/s1/kadrlica/projects/mw_substructure/y3a2/sim_population/v10_des/sim_population_v10_des_mc_source_id_0000001-0010000.fits'
    sim_dir: '/home/s1/kadrlica/projects/mw_substructure/y3a2/sim_population/v10_des'
    nside          : 32
    #datadir        : '/home/s1/kadrlica/projects/y3a2/data/gold/v2.0/skim_ext_0_3'
    datadir        : '/home/s1/kadrlica/projects/y3a2/data/gold/v2.0/healpix'
    isoname: 'Bressan2012'
    isosurvey: 'des'
    object_list: 'object_list.fits'
    candidate_list : 'candidate_list_r-i.fits'
    mag_max : 24.5

    basis_1: 'RA'
    basis_2: 'DEC'

    # Dev #############################################################
    # # change to band_1, band_2
    color_1: 'R'
    color_2: 'I'
    #mag: 'SOF_PSF_MAG_CORRECTED_'
    mag: 'SOF_PSF_MAG_'
    mag_err: 'SOF_PSF_MAG_ERR_'
    mag_dered: 'MAG_DERED_'

    #mag_1_err: '' #'SOF_PSF_MAG_ERR_G'
    #mag_2_err: '' #'SOF_PSF_MAG_ERR_R'
    ###################################################################

    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    mag_g_err : 'SOF_PSF_MAG_ERR_G'
    mag_r_err : 'SOF_PSF_MAG_ERR_R'

    star_galaxy_classification : 'EXTENDED_CLASS_MASH_SOF'

    #maglim_g : '/home/s1/kadrlica/projects/y3q2/v6/release/depth/y2q1_maglim_g_n1024_ring.fits.gz'
    #maglim_r : '/home/s1/kadrlica/projects/y2q/v6/release/depth/y2q1_maglim_r_n1024_ring.fits.gz'

    fracdet_gz : 'y3a2_griz_o.4096_t.32768_coverfoot_EQU.fits.gz'
    fracdet : 'y3a2_griz_o.4096_t.32768_coverfoot_EQU_decompressed.fits'

y3a2:
    mode : 1 # 0: real, 1: real+sim
    sim_population : 'v3/sim_population_v3.fits'
    sim_dir: 'v3'
    nside          : 32
    datadir        : '/home/s1/kadrlica/projects/y3a2/dsphs/v2/skim'
    candidate_list : 'candidate_list.fits'
    mag_max : 24.5
    #candidate_list : '/home/s1/kadrlica/projects/y3a2/dsphs/v2/v2.1/search/ugali_candidates.fits' # ugali
    isoname: 'Bressan2012'
    isosurvey: 'des'

    basis_1: 'RA'
    basis_2: 'DEC'
    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    mag_g_err             : 'PSF_MAG_ERR_G'
    mag_r_err             : 'PSF_MAG_ERR_R'

    mag_g_dred_flag : 'PSF_MAG_SFD_G'
    mag_r_dred_flag : 'PSF_MAG_SFD_R'
    mag_err_g_flag  : 'PSF_MAG_ERR_G'
    mag_err_r_flag  : 'PSF_MAG_ERR_R'
    flags_g         : 'SEXTRACTOR_FLAGS_G'
    flags_r         : 'SEXTRACTOR_FLAGS_R'

    star_galaxy_classification : 'EXTENDED_CLASS_MASH'

    maglim_g : '/home/s1/kadrlica/projects/y3q2/v6/release/depth/y2q1_maglim_g_n1024_ring.fits.gz'
    maglim_r : '/home/s1/kadrlica/projects/y2q/v6/release/depth/y2q1_maglim_r_n1024_ring.fits.gz'

    fracdet : 'y3a2_griz_o.4096_t.32768_coverfoot_EQU.fits.gz'

bliss: # Need to update this
    mode: 0
    sim_population: None
    sim_dir: None
    nside          : 32
    #datadir        : '/home/s1/kadrlica/projects/bliss/cat/v3/cat'
    datadir        : '/home/s1/kadrlica/projects/bliss/cat/v4/cat'
    #datadir        : '/home/s1/kadrlica/projects/bliss/cat/v4/hpx/i'
    #datadir        : '/home/s1/kadrlica/projects/bliss/cat/v3/hpx/i'
    candidate_list : 'candidate_list.fits'
    mag_max : 24.5
    isoname: 'Bressan2012'
    isosurvey: 'des'

    basis_1: 'RA'
    basis_2: 'DEC'
    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    mag_g_err : 'WAVG_MAGERR_PSF_G'
    mag_r_err : 'WAVG_MAGERR_PSF_R'
    #mag_g_err             : 'PSF_MAG_ERR_G'
    #mag_r_err             : 'PSF_MAG_ERR_R'

    #mag_g_dred_flag            : 'PSF_MAG_SFD_G'
    #mag_r_dred_flag            : 'PSF_MAG_SFD_R'
    ##mag_g_flag                : 'CM_MAG_G'
    ##mag_r_flag                : 'CM_MAG_R'
    #mag_err_g_flag             : 'PSF_MAG_ERR_G'
    #mag_err_r_flag             : 'PSF_MAG_ERR_R'
    ##extinction_g_flag         : 'EXTINCTION_G'
    ##extinction_r_flag         : 'EXTINCTION_R'
    #star_galaxy_classification : 'EXTENDED_CLASS_MASH' #spread_model_r_flag

    #spread_model_r_flag        : 'CM_T' # use for BISS/MagLiteS
    #spread_model_r_err_flag    : 'CM_T_ERR'
    #flags_g                    : 'SEXTRACTOR_FLAGS_G'
    #flags_r                    : 'SEXTRACTOR_FLAGS_R'

    fracdet : None

maglites: # Update
    nside          : 32
    datadir        : '/home/s1/kadrlica/projects/maglites/r4/v1/cat'
    candidate_list : 'candidate_list.fits'
    mag_max : 24.5
    isoname: 'Bressan2012'
    isosurvey: 'des'

    basis_1: 'RA'
    basis_2: 'DEC'
    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    #mag_g_dred_flag            : 'PSF_MAG_SFD_G'
    #mag_r_dred_flag            : 'PSF_MAG_SFD_R'
    mag_g_flag                  : 'WAVG_MAG_PSF_G'
    mag_r_flag                  : 'WAVG_MAG_PSF_R'
    mag_err_g_flag              : 'WAVG_MAGERR_PSF_G'
    mag_err_r_flag              : 'WAVG_MAGERR_PSF_R'
    extinction_g_flag           : 'EXTINCTION_G'
    extinction_r_flag           : 'EXTINCTION_R'
    #star_galaxy_classification : 'EXTENDED_CLASS_MASH' # adapt this for dif data sets

    spread_model_r_flag         : 'WAVG_SPREAD_MODEL_R' # use for BISS/MagLiteS
    spread_model_r_err_flag     : 'SPREADERR_MODEL_R'
    flags_g                     : 'SEXTRACTOR_FLAGS_G'
    flags_r                     : 'SEXTRACTOR_FLAGS_R'

    fracdet : None

panstarrs:
    mode           : 1
    #sim_population : '/home/s1/kadrlica/projects/mw_substructure/y3a2/sim_population/v9_ps1/sim_population_v9_ps1_mc_source_id_0000001-0010000.fits'
    #sim_dir        : '/home/s1/kadrlica/projects/mw_substructure/y3a2/sim_population/v9_ps1'
    sim_dir : '/home/s1/kadrlica/projects/mw_substructure/y3a2/sim_population/v10_ps1'
    sim_population : '/home/s1/kadrlica/projects/mw_substructure/y3a2/sim_population/v10_ps1/sim_population_v10_ps1_mc_source_id_0000001-0010000.fits'
    nside          : 32
    #datadir        : '/data/des40.b/data/pan-starrs/dr1/healpix'
    datadir        : '/home/s1/kadrlica/projects/ps1/dr1/v0/skim_ext_0_1'
    #datadir        : '/Users/keithbechtol/Documents/DES/external_data/pan-starrs/data/healpix'
    #isodir         : '/Users/keithbechtol/Documents/DES/projects/mw_substructure/ugalidir/isochrones/ps1/dotter2016/'
    isoname        : 'Bressan2012' #'Dotter2016'
    isosurvey      : 'ps1'
    candidate_list : 'candidate_list_sim.fits'
    mag_max : 22.5

    basis_1: 'RA'
    basis_2: 'DEC'
    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    mag_g_err : 'GFPSFMAGERR'
    mag_r_err : 'RFPSFMAGERR'
    flags_g : 'GFLAGS'
    flags_r : 'RFLAGS'

    fracdet_gz : 'panstarrs_pseudo_fracdet.fits.gz'
    fracdet : 'panstarrs_pseudo_fracdet.fits'
    #fracdet : '/Users/keithbechtol/Documents/DES/external_data/pan-starrs/simple/sid/simple_v2/panstarrs_pseudo_fracdet.fits.gz'
