setup:
    simple_dir : '/home/s1/smau/software/simple'

output:
    results_dir : 'results_dir'
    log_dir     : 'log_dir'
    save_dir    : 'save_dir'

batch:
    jobs: 20 # <= 20 for DES cluster computers!

survey: 'y3_gold_2_0' # parameter to change for runs across different data

y3_gold_2_0:
    mode : 1 # 0: real, 1: real+sim
    sim_catalog : None
    sim_population : '/data/des60.b/data/bechtol/projects/mw_substructure/y3a2/sim_population/v6/sim_population_v6_mc_source_id_000001-100000.fits'
    sim_dir: '/data/des60.b/data/bechtol/projects/mw_substructure/y3a2/sim_population/v6'
    nside          : 32
    datadir        : '/home/s1/kadrlica/projects/y3a2/data/gold/v2.0/skim_ext_0_3'
    candidate_list : 'candidate_list.fits'
    mag_max : 24.5

    basis_1: 'RA'
    basis_2: 'DEC'

    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    mag_g_err : 'SOF_PSF_MAG_ERR_G'
    mag_r_err : 'SOF_PSF_MAG_ERR_R'

    mag_g_dred_flag : 'SOF_PSF_MAG_CORRECTED_G'
    mag_r_dred_flag : 'SOF_PSF_MAG_CORRECTED_G'
    mag_err_g_flag :  'SOF_PSF_MAG_ERR_G'
    mag_err_r_flag :  'SOF_PSF_MAG_ERR_R'
    flags_g : 'FLAGS_GOLD'
    flags_r : 'FLAGS_GOLD'

    star_galaxy_classification : 'EXTENDED_CLASS_MASH_SOF'

    maglim_g : '/home/s1/kadrlica/projects/y3q2/v6/release/depth/y2q1_maglim_g_n1024_ring.fits.gz'
    maglim_r : '/home/s1/kadrlica/projects/y2q/v6/release/depth/y2q1_maglim_r_n1024_ring.fits.gz'

    fracdet_gz : 'y3a2_griz_o.4096_t.32768_coverfoot_EQU.fits.gz'
    fracdet : 'y3a2_griz_o.4096_t.32768_coverfoot_EQU_decompressed.fits'

y3a2:
    mode : 1 # 0: real, 1: real+sim
    sim_catalog : 'sim_catalog.fits'
    sim_population : 'v3/sim_population_v3.fits'
    sim_dir: 'v3'
    nside          : 32
    datadir        : '/home/s1/kadrlica/projects/y3a2/dsphs/v2/skim'
    candidate_list : 'candidate_list.fits'
    mag_max : 24.5
    #candidate_list : '/home/s1/kadrlica/projects/y3a2/dsphs/v2/v2.1/search/ugali_candidates.fits' # ugali

    basis_1: 'RA'
    basis_2: 'DEC'
    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    mag_g_err             : 'PSF_MAG_ERR_G'
    mag_r_err             : 'PSF_MAG_ERR_R'

    mag_g_dred_flag : 'PSF_MAG_SFD_G'
    mag_r_dred_flag : 'PSF_MAG_SFD_R'
    mag_err_g_flag  : 'PSF_MAG_ERR_G'
    mag_err_r_flag  : 'PSF_MAG_ERR_R'
    flags_g         : 'SEXTRACTOR_FLAGS_G'
    flags_r         : 'SEXTRACTOR_FLAGS_R'

    star_galaxy_classification : 'EXTENDED_CLASS_MASH'

    maglim_g : '/home/s1/kadrlica/projects/y3q2/v6/release/depth/y2q1_maglim_g_n1024_ring.fits.gz'
    maglim_r : '/home/s1/kadrlica/projects/y2q/v6/release/depth/y2q1_maglim_r_n1024_ring.fits.gz'

    fracdet : 'y3a2_griz_o.4096_t.32768_coverfoot_EQU.fits.gz'

bliss: # Need to update this
    nside          : 32
    datadir        : '/home/s1/kadrlica/projects/bliss/cat/v2/cat'
    candidate_list : 'candidate_list.fits'
    mag_max : 24.5

    basis_1: 'RA'
    basis_2: 'DEC'
    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    mag_g_err             : 'PSF_MAG_ERR_G'
    mag_r_err             : 'PSF_MAG_ERR_R'

    #mag_g_dred_flag            : 'PSF_MAG_SFD_G'
    #mag_r_dred_flag            : 'PSF_MAG_SFD_R'
    ##mag_g_flag                : 'CM_MAG_G'
    ##mag_r_flag                : 'CM_MAG_R'
    #mag_err_g_flag             : 'PSF_MAG_ERR_G'
    #mag_err_r_flag             : 'PSF_MAG_ERR_R'
    ##extinction_g_flag         : 'EXTINCTION_G'
    ##extinction_r_flag         : 'EXTINCTION_R'
    #star_galaxy_classification : 'EXTENDED_CLASS_MASH' #spread_model_r_flag

    #spread_model_r_flag        : 'CM_T' # use for BISS/MagLiteS
    #spread_model_r_err_flag    : 'CM_T_ERR'
    #flags_g                    : 'SEXTRACTOR_FLAGS_G'
    #flags_r                    : 'SEXTRACTOR_FLAGS_R'

    fracdet : None

maglites: # Update
    nside          : 32
    datadir        : '/home/s1/kadrlica/projects/maglites/r4/v1/cat'
    candidate_list : 'candidate_list.fits'
    mag_max : 24.5

    basis_1: 'RA'
    basis_2: 'DEC'
    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    #mag_g_dred_flag            : 'PSF_MAG_SFD_G'
    #mag_r_dred_flag            : 'PSF_MAG_SFD_R'
    mag_g_flag                  : 'WAVG_MAG_PSF_G'
    mag_r_flag                  : 'WAVG_MAG_PSF_R'
    mag_err_g_flag              : 'WAVG_MAGERR_PSF_G'
    mag_err_r_flag              : 'WAVG_MAGERR_PSF_R'
    extinction_g_flag           : 'EXTINCTION_G'
    extinction_r_flag           : 'EXTINCTION_R'
    #star_galaxy_classification : 'EXTENDED_CLASS_MASH' # adapt this for dif data sets

    spread_model_r_flag         : 'WAVG_SPREAD_MODEL_R' # use for BISS/MagLiteS
    spread_model_r_err_flag     : 'SPREADERR_MODEL_R'
    flags_g                     : 'SEXTRACTOR_FLAGS_G'
    flags_r                     : 'SEXTRACTOR_FLAGS_R'

    fracdet : None

panstarrs:
    nside          : 32
    datadir        : '/Users/keithbechtol/Documents/DES/external_data/pan-starrs/data/healpix/'
    candidate_list : 'candidate_list.fits'
    mag_max : 22

    basis_1: 'RA'
    basis_2: 'DEC'
    mag_g : 'MAG_G'
    mag_r : 'MAG_R'
    mag_g_err : 'GFPSFMAGERR'
    mag_r_err : 'RFPSFMAGERR'
    flags_g : 'GFLAGS'
    flags_r : 'RFLAGS'

    fracdet : '/Users/keithbechtol/Documents/DES/external_data/pan-starrs/simple/sid/simple_v2/panstarrs_pseudo_fracdet.fits.gz'
